import {
  BadgeDollarSign,
  BookOpen,
  Brain,
  Briefcase,
  Calendar,
  ChartLine,
  Cloud,
  Code2,
  Database,
  Dices,
  Eye,
  FileCheck,
  Gauge,
  Globe2,
  GraduationCap,
  Landmark,
  Layers,
  LineChart,
  Lock,
  MessageSquare,
  RadioTower,
  RefreshCw,
  Rocket,
  Scale,
  Shield,
  ShieldCheck,
  Target,
  Timer,
  TrendingDown,
  TrendingUp,
  Truck,
  UserCog,
  Users,
  Wallet,
  type LucideIcon,
} from 'lucide-react';

export const featureIcons = {
  brain: Brain,
  shield: Shield,
  shieldCheck: ShieldCheck,
  fraud: ShieldCheck,
  scale: Scale,
  radio: RadioTower,
  credit: Landmark,
  users: Users,
  churn: TrendingDown,
  growth: TrendingUp,
  gaming: Dices,
  logistics: Truck,
  forecast: ChartLine,
  globe: Globe2,
  architecture: Layers,
  explain: Eye,
  monitor: Gauge,
  runbook: BookOpen,
  datastore: Database,
  pilot: Rocket,
  deploy: Cloud,
  operate: RefreshCw,
  code: Code2,
  lock: Lock,
  fileCheck: FileCheck,
  timer: Timer,
  target: Target,
  settings: RefreshCw,
  wallet: Wallet,
  learning: GraduationCap,
  calendar: Calendar,
  honest: MessageSquare,
  briefcase: Briefcase,
  chart: LineChart,
  engineer: UserCog,
  depth: Layers,
  pricing: BadgeDollarSign,
  regulator: Scale,
  horizon: Calendar,
} as const satisfies Record<string, LucideIcon>;

export type FeatureIconKey = keyof typeof featureIcons;

export function resolveFeatureIcon(icon?: FeatureIconKey): LucideIcon {
  if (!icon) {
    return Brain;
  }

  return featureIcons[icon] ?? Brain;
}
