export const siteConfig = {
  name: 'Klugminds',
  tagline: 'AI systems that ship, scale, and stay reliable in production.',
  description:
    'Klugminds designs, builds, and operates production-grade machine learning for financial services, iGaming, e-commerce, logistics, and healthcare.',
  seoDescription:
    'Production-grade AI for regulated industries. Fraud, AML, iGaming integrity, and credit risk models with explainability, monitoring, and governance documentation. Global delivery from India.',
  alternateNames: ['Klugminds AI', 'Klugmindlabs', 'Klug Minds', 'KLUGMINDLABS'] as const,
  keywords: [
    'Klugminds',
    'Klugminds AI',
    'klugminds.com',
    'KLUGMINDLABS',
    'KLUGMINDLABS PRIVATE LIMITED',
    'Klugmindlabs',
    'Klug Minds',
    'AI company India',
    '37AANCK0145Q1ZZ',
    'GSTIN 37AANCK0145Q1ZZ',
    'AI engineering',
    'data science',
    'DevSecOps',
    'fintech',
    'AML',
    'credit risk',
    'iGaming',
    'responsible gaming',
  ] as const,
  contactEmail: 'hello@klugminds.com',
  careersEmail: 'careers@klugminds.com',
  locale: 'en',
  founded: 2026,
  locations: {
    delivery: ['Bengaluru'] as const,
    clients: ['Europe', 'United Arab Emirates', 'Canada', 'India'] as const,
  },
} as const;
